### ISSUE TITLE
Where can I find the data?

### ISSUE THREAD

**Issue by xu-cpp** [holygeek01/reuters-doc2vec#1]
Where can I find the data?

**Comment by rejinjosek** [comment]
Hi, The data is available in the NLTK corpus.  
We import it in the train file:
from nltk.corpus import reuters

**Comment by xu-cpp** [comment]
OK, thanks!

**Comment by rejinjosek** [comment]
Most Welcome :)

On 12/6/20, xu-cpp <notifications@github.com> wrote:
> OK, thanks!
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/holygeek01/reuters-doc2vec/issues/1#issuecomment-739445819


-- 
Stay Well!
Rejin
